using System;
using System.Collections.Generic;
using System.Text;

namespace KernelTrace.SourceGenerators;

/// <summary>
/// Emits the C# partial struct body for a given <see cref="CStruct"/>.
/// </summary>
internal static class StructEmitter
{
    // ── C type → C# type mapping ─────────────────────────────────────────────
    private static readonly Dictionary<string, string> TypeMap =
        new(StringComparer.Ordinal)
        {
            ["__u8"]   = "byte",   ["u8"]   = "byte",   ["char"]  = "byte",
            ["__s8"]   = "sbyte",  ["s8"]   = "sbyte",
            ["__u16"]  = "ushort", ["u16"]  = "ushort",
            ["__s16"]  = "short",  ["s16"]  = "short",
            ["__be16"] = "ushort", ["__le16"] = "ushort",
            ["__u32"]  = "uint",   ["u32"]  = "uint",   ["int"]   = "int",
            ["__s32"]  = "int",    ["s32"]  = "int",
            ["__be32"] = "uint",   ["__le32"] = "uint",
            ["__u64"]  = "ulong",  ["u64"]  = "ulong",  ["long"]  = "long",
            ["__s64"]  = "long",   ["s64"]  = "long",
            ["__be64"] = "ulong",  ["__le64"] = "ulong",
        };

    /// <summary>
    /// Emits a complete compilable C# source file for the given struct.
    /// </summary>
    /// <param name="ns">C# namespace of the consuming partial struct.</param>
    /// <param name="csTypeName">C# type name (PascalCase).</param>
    /// <param name="cStruct">Parsed C struct to emit fields for.</param>
    /// <param name="unsupportedFields">
    /// Receives names of any fields that could not be mapped (for diagnostics).
    /// </param>
    public static string Emit(
        string ns,
        string csTypeName,
        CStruct cStruct,
        out List<string> unsupportedFields)
    {
        unsupportedFields = new List<string>();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by KernelTrace.SourceGenerators");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using KernelTrace.Events;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated C# projection of the eBPF struct <c>{cStruct.Name}</c>.");
        sb.AppendLine($"/// Total size: {cStruct.TotalBytes} bytes.");
        sb.AppendLine("/// Do not add fields manually — edit the .bpf.c source and rebuild.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 1)]");
        sb.AppendLine($"public partial struct {csTypeName} : IKernelEvent");
        sb.AppendLine("{");

        // ── Fields ────────────────────────────────────────────────────────────
        foreach (var field in cStruct.Fields)
        {
            string csFieldName = ToPascalCase(field.CName);

            if (field.ArrayLen.HasValue)
            {
                // Fixed-size array: use 'fixed byte Name[N]' for byte-type arrays,
                // or a manual expansion for wider element types.
                if (TypeMap.TryGetValue(field.CType, out string? elemType) && elemType == "byte")
                {
                    sb.AppendLine($"    /// <summary>C field: <c>{field.CType} {field.CName}[{field.ArrayLen}]</c></summary>");
                    sb.AppendLine($"    public unsafe fixed byte {csFieldName}[{field.ArrayLen}];");
                }
                else if (TypeMap.TryGetValue(field.CType, out elemType))
                {
                    // For non-byte element types emit individual fields.
                    for (int i = 0; i < field.ArrayLen; i++)
                    {
                        sb.AppendLine($"    public {elemType} {csFieldName}{i};");
                    }
                }
                else
                {
                    unsupportedFields.Add($"{field.CType} {field.CName}[{field.ArrayLen}]");
                    sb.AppendLine($"    // UNSUPPORTED: {field.CType} {field.CName}[{field.ArrayLen}]");
                }
            }
            else
            {
                if (TypeMap.TryGetValue(field.CType, out string? csType))
                {
                    string bigEndianNote = field.CType.Contains("be")
                        ? " Big-endian — use System.Net.IPAddress.NetworkToHostOrder() before use."
                        : "";
                    sb.AppendLine($"    /// <summary>C field: <c>{field.CType} {field.CName}</c>.{bigEndianNote}</summary>");
                    sb.AppendLine($"    public {csType} {csFieldName};");
                }
                else
                {
                    unsupportedFields.Add($"{field.CType} {field.CName}");
                    sb.AppendLine($"    // UNSUPPORTED: {field.CType} {field.CName}");
                }
            }

            sb.AppendLine();
        }

        // ── Compile-time size assertion ───────────────────────────────────────
        // This fails at compile time if sizeof(T) != expected, catching regressions.
        if (cStruct.TotalBytes > 0)
        {
            sb.AppendLine($"    // Compile-time layout guard: sizeof({csTypeName}) must equal {cStruct.TotalBytes}.");
            sb.AppendLine($"    // If you see CS0208 here the struct layout has drifted from the eBPF definition.");
            sb.AppendLine($"    private static readonly int _sizeCheck =");
            sb.AppendLine($"        (global::System.Runtime.CompilerServices.Unsafe.SizeOf<{csTypeName}>() == {cStruct.TotalBytes})");
            sb.AppendLine($"            ? 0");
            sb.AppendLine($"            : throw new global::System.InvalidOperationException(");
            sb.AppendLine($"                $\"[KernelTrace] Struct '{csTypeName}' size mismatch: \" +");
            sb.AppendLine($"                $\"expected {cStruct.TotalBytes} bytes, got {{global::System.Runtime.CompilerServices.Unsafe.SizeOf<{csTypeName}>()}}.\");");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        var parts = name.Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
            {
                continue;
            }
            sb.Append(char.ToUpperInvariant(part[0]));
            sb.Append(part, 1, part.Length - 1);
        }

        return sb.Length > 0 ? sb.ToString() : name;
    }
}
