using System.Net;
using System.Runtime.InteropServices;
using KernelTrace.Events;
using KernelTrace.Probes;
using KernelTrace.Sessions;

// ──────────────────────────────────────────────────────────────────────────────
//  NetworkMonitor — Sample
//  Streams every outbound TCP connect() syscall to the console.
//  Shows: IAsyncEnumerable<T> API, source-generated struct, IP formatting.
//
//  Requirements:
//    - Linux with kernel >= 5.8
//    - CAP_BPF capability (or run as root)
//    - Compiled eBPF object: ../../native/probes/network_monitor.bpf.o
// ──────────────────────────────────────────────────────────────────────────────

using var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) => { e.Cancel = true; cts.Cancel(); };

Console.WriteLine("╔══════════════════════════════════════════════╗");
Console.WriteLine("║       KernelTrace — Network Monitor          ║");
Console.WriteLine("║  Press Ctrl+C to stop                        ║");
Console.WriteLine("╚══════════════════════════════════════════════╝");
Console.WriteLine();

await using var session = await KernelTraceSession.CreateAsync(new SessionOptions
{
    ProbePath = Path.Combine(AppContext.BaseDirectory, "network_monitor.bpf.o"),
    Probes =
    [
        new TracepointSpec { Category = "syscalls", Name = "sys_enter_connect" },
        new TracepointSpec { Category = "syscalls", Name = "sys_exit_connect" },
    ],
    ChannelCapacity = 16_384,
    PollTimeoutMs   = 50,
});

Console.WriteLine($"Session started. Metrics: {session.Metrics.TotalReceived} events received.");
Console.WriteLine();
Console.WriteLine($"{"TIME",-12} {"PID",-8} {"COMM",-16} {"SRC IP",-18} {"DST IP",-18} {"DST PORT",-10} ALERT");
Console.WriteLine(new string('─', 90));

try
{
await foreach (var ev in session.ReadAsync<SocketConnectEvent>(cts.Token))
{
    string srcIp  = FormatIp(ev.SrcIp);
    string dstIp  = FormatIp(ev.DstIp);
    string comm   = ReadNullTerminatedString(ev, 16);
    string time   = DateTime.Now.ToString("HH:mm:ss.fff");

    string alert = ev.DstPort switch
    {
        80  => "⚠ UNENCRYPTED HTTP",
        23  => "🚨 TELNET",
        21  => "🚨 FTP",
        _   => "",
    };

    ConsoleColor color = alert.StartsWith("🚨") ? ConsoleColor.Red
                       : alert.StartsWith('⚠')  ? ConsoleColor.Yellow
                       : ConsoleColor.Gray;

    Console.ForegroundColor = color;
    Console.WriteLine(
        $"{time,-12} {ev.Pid,-8} {comm,-16} {srcIp,-18} {dstIp,-18} {ev.DstPort,-10} {alert}");
    Console.ResetColor();
}
}
catch (OperationCanceledException) { }

// ── Helpers ───────────────────────────────────────────────────────────────────

static string FormatIp(uint ip) =>
    new IPAddress(BitConverter.GetBytes(ip)).ToString();

static unsafe string ReadNullTerminatedString(in SocketConnectEvent ev, int maxLen)
{
    // Access the fixed comm buffer safely.
    fixed (SocketConnectEvent* ptr = &ev)
    {
        byte* comm = ptr->Comm;
        int len = 0;
        while (len < maxLen && comm[len] != 0)
        {
            len++;
        }
        return System.Text.Encoding.ASCII.GetString(comm, len);
    }
}

// ── Event struct — auto-generated by KernelTrace.SourceGenerators ─────────────
// The source generator reads network_monitor.bpf.c and generates this layout.
// If not using the generator, declare manually with matching Pack=1 layout.

/// <summary>
/// Kernel event emitted on every <c>sys_enter_connect</c> syscall.
/// Generated from <c>struct sock_connect_event</c> in <c>network_monitor.bpf.c</c>.
/// </summary>
[KernelEvent("sock_connect_event")]
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public unsafe partial struct SocketConnectEvent
{
    public ulong  TimestampNs;
    public uint   Pid;
    public uint   Tgid;
    public uint   Uid;
    public uint   SrcIp;
    public uint   DstIp;
    public ushort SrcPort;
    public ushort DstPort;
    public fixed byte Comm[16];
    public byte   Family;
}
